#!/bin/bash
set -e
set -u

# File descriptor limit is propagated via sbatch --propagate=RLIMIT_NOFILE
# No need to set it here

# Benchmark script for llama2-70b using MLPerf harness

echo "=========================================="
echo "bench_e2e.sh started"
echo "=========================================="

if [ "$#" -lt 1 ]; then
    echo "ERROR: Missing required arguments"
    echo "Usage: $0 output_dir"
    exit 1
fi

output_dir=$1
echo "Output directory: $output_dir"

# Debug logging disabled - uncomment if needed for troubleshooting
# script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# if [ -f "${script_dir}/dump_env_debug.sh" ]; then
#     source "${script_dir}/dump_env_debug.sh" "${output_dir}" "HARNESS"
# fi

# Only run on SLURM process 0
if [[ ${SLURM_PROCID} != "0" ]]; then
    echo "Process ID is ${SLURM_PROCID}, skipping (only process 0 runs harness)"
    exit 0
fi
echo "Process ID: ${SLURM_PROCID} - proceeding with benchmark"

# Wait for server URLs file (generated by gen_server_config.py)
server_urls_file=${output_dir}/server_urls.txt
echo "Looking for server URLs file: ${server_urls_file}"

timeout=1800
start_time=$(date +%s)
dots=0
echo "Waiting for server URLs file to appear..."
while [ ! -f ${server_urls_file} ]; do
    current_time=$(date +%s)
    elapsed=$((current_time - start_time))
    if [ $elapsed -ge $timeout ]; then
        echo ""
        echo "      ✗ ERROR: Server URLs file not found after ${timeout}s"
        exit 1
    fi
    if [ $((elapsed % 10)) -eq 0 ]; then
        printf "."
        dots=$((dots + 1))
    fi
    sleep 2
done
if [ $dots -gt 0 ]; then echo ""; fi
echo "✓ Server URLs file found: ${server_urls_file}"

# Read server URLs from file
server_urls=$(cat ${server_urls_file} | tr -d '\r\n')
echo "Server URLs: ${server_urls}"

if [ -z "$server_urls" ]; then
    echo "✗ ERROR: Server URLs file is empty"
    exit 1
fi

# Extract first URL for health check
first_url=$(echo ${server_urls} | cut -d',' -f1)
hostname=$(echo ${first_url} | cut -d':' -f1)
port=$(echo ${first_url} | cut -d':' -f2)
echo "✓ Using first server for health check: ${hostname}:${port}"

# Wait for server to be healthy
health_url="http://${hostname}:${port}/health"
echo "Checking: ${health_url}"
echo "Starting health check..."

# Test if curl is available
if ! command -v curl &> /dev/null; then
    echo "✗ ERROR: curl command not found"
    exit 7
fi

# Test a simple curl first
echo "Testing curl connectivity..."
test_result=$(curl -s -o /dev/null -w "%{http_code}" "${health_url}" 2>&1 || echo "CURL_FAILED")
echo "Initial curl test result: ${test_result}"

echo -n "Waiting"
timeout=600  # Reduced to 10 minutes
start_time=$(date +%s)
last_log_time=$start_time

while true; do
    http_code=$(curl -s -o /dev/null -w "%{http_code}" "${health_url}" 2>/dev/null || echo "000")
    if [ "$http_code" = "200" ]; then
        break
    fi
    current_time=$(date +%s)
    elapsed=$((current_time - start_time))
    
    if [ $elapsed -ge $timeout ]; then
        echo ""
        echo "✗ ERROR: Server not healthy after ${timeout}s"
        echo ""
        echo "Debug: Check server logs:"
        echo "  cat ${output_dir}/output_server.log"
        echo "  cat ${output_dir}/output_gen_*.log"
        echo "  cat ${output_dir}/output_ctx_*.log"
        echo ""
        echo "Check if workers registered:"
        echo "  ls ${output_dir}/hostnames/"
        echo ""
        echo "Last HTTP response code: ${http_code:-none}"
        exit 1
    fi
    
    # Print dot every 5 seconds, but also print status every 30 seconds
    if [ $((elapsed % 30)) -eq 0 ] && [ $elapsed -gt 0 ]; then
        if [ $((current_time - last_log_time)) -ge 30 ]; then
            echo ""
            echo "Still waiting... (${elapsed}s elapsed, last response: ${http_code:-none})"
            echo "Checking: ${health_url}"
            echo -n "Waiting"
            last_log_time=$current_time
        fi
    elif [ $((elapsed % 5)) -eq 0 ]; then
        printf "."
    fi
    
    sleep 2
done
echo ""
echo "✓ Server is healthy!"
echo ""
echo "Starting MLPerf harness..."

# Determine harness target based on audit flag
harness_target="run_harness"
if [ "${audit:-false}" = "true" ]; then
    harness_target="run_audit_harness"
    echo "AUDIT MODE ENABLED - Using run_audit_harness"
fi

echo "Command: make ${harness_target} RUN_ARGS=\"--benchmarks=llama2-70b --scenarios=${scenario} --trtllm_server_urls=${server_urls} --min_query_count=${num_reqs} --server_target_qps=${target_qps} --trtllm_runtime_flags=max_concurrency:${concurrency},traffic_distribution_policy:isl_load_balancing\""
echo ""

# Check if make is available and we're in the right directory
if ! command -v make &> /dev/null; then
    echo "✗ ERROR: make command not found"
    exit 8
fi

echo "Current working directory: $(pwd)"
if [ ! -f "Makefile" ]; then
    echo "✗ ERROR: Makefile not found in current directory"
    echo "   Expected to be in: /work (closed/NVIDIA)"
    exit 9
fi

echo "Environment variables:"
echo "  LOG_DIR=${output_dir}"
echo "  SYSTEM_NAME=${SYSTEM_NAME_X72}"
echo "  concurrency=${concurrency}"
echo "  target_qps=${target_qps}"
echo "  num_reqs=${num_reqs}"
echo "  scenario=${scenario}"
echo "  test_mode=${test_mode}"
echo "  warmup_iters=${warmup_iters:-0}"
echo ""
echo "=== MLPerf Harness Output ==="

# Run MLPerf harness for llama2-70b
# Environment variables: concurrency, target_qps, num_reqs, scenario, test_mode, warmup_iters, audit, SYSTEM_NAME_X72
LOG_DIR=${output_dir} \
SYSTEM_NAME=${SYSTEM_NAME_X72} \
make ${harness_target} RUN_ARGS="\
    --benchmarks=llama2-70b \
    --scenarios=${scenario} \
    --core_type=trtllm_endpoint \
    --trtllm_server_urls=${server_urls} \
    --test_mode=${test_mode} \
    --warmup_iterations=${warmup_iters:-0} \
    --min_query_count=${num_reqs} \
    --server_target_qps=${target_qps} \
    --trtllm_runtime_flags=max_concurrency:${concurrency},traffic_distribution_policy:isl_load_balancing"

# Save job info
job_id=${SLURM_JOB_ID}
if [ -n "${job_id}" ]; then
    echo "${SLURM_JOB_NODELIST}" > ${output_dir}/job_${job_id}.txt
fi

echo ""
echo "=== MLPerf Harness Completed ==="
echo ""
echo "✓ Benchmark completed!"
echo ""
echo "bench_e2e.sh completed successfully"
echo ""
echo "Workers are still running. To stop them:"
echo "  pkill -9 trtllm-serve"

